module.exports = {
  apps: [
    {
      name: 'misfit-api',
      script: './artifacts/api-server/dist/index.js',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 5000,
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      max_restarts: 10,
      min_uptime: '10s',
      listen_timeout: 3000,
      kill_timeout: 5000,
      shutdown_with_message: true,
      wait_ready: true,
      events: {
        restart: 'echo "App restarted"',
        reload: 'echo "App reloaded"',
        stop: 'echo "App stopped"',
        exit: 'echo "App exited"',
        'restart overlimit': 'pm2 stop misfit-api',
      },
    },
  ],
  deploy: {
    production: {
      user: 'ubuntu',
      host: process.env.DEPLOY_HOST || 'localhost',
      ref: 'origin/main',
      repo: process.env.GITHUB_REPO || 'git@github.com:user/misfit-ministries.git',
      path: '/home/ubuntu/misfit-ministries-prod',
      'post-deploy': 'pnpm install && pnpm build && pm2 restart ecosystem.config.js --env production',
      'pre-deploy-local': 'echo "Deploying to production"',
    },
  },
};
