import { Router } from 'express';
import prayersRouter from './prayers.js';
import testimoniesRouter from './testimonies.js';
import resourcesRouter from './resources.js';
import contentRouter from './content.js';
import siteCopyRouter from './site-copy.js';
import nuraRouter from './nura.js';
import nuraVoiceRouter from './nura-voice.js';
import forgeRouter from './forge.js';
import stripeRouter from './stripe.js';
import statsRouter from './stats.js';
import crisisRouter from './crisis.js';
import autopilotRouter from './autopilot.js';
import forgeGenerateRouter from './forge-generate.js';
import narcanRespondersRouter from './narcan-responders.js';
import narcanAlertsRouter from './narcan-alerts.js';
import narcanSubscribeRouter from './narcan-subscribe.js';
import responderStoriesRouter from './responder-stories.js';
import storeRouter from './store.js';
import narcanSupplyChainRouter from './narcan-supply-chain.js';
import stripeWebhookRouter from './stripe-webhook.js';
import autopilotSchedulerRouter from './autopilot-scheduler.js';
import notificationsRouter from './notifications.js';
import emailNotificationsRouter from './email-notifications.js';
import analyticsRouter from './analytics.js';
import twoFactorRouter from './two-factor.js';
import auditLogsRouter from './audit-logs.js';
import heatmapRouter from './heatmap.js';
import videoTestimonialsRouter from './video-testimonials.js';

const router: ReturnType<typeof Router> = Router();

// Mount all route modules
router.use('/prayers', prayersRouter);
router.use('/testimonies', testimoniesRouter);
router.use('/resources', resourcesRouter);
router.use('/content', contentRouter);
router.use('/site-copy', siteCopyRouter);
router.use('/nura', nuraRouter);
router.use('/nura', nuraVoiceRouter);
router.use('/forge', forgeRouter);
router.use('/forge/autopilot', autopilotRouter);
router.use('/forge/media', forgeGenerateRouter);
router.use('/stripe', stripeRouter);
router.use('/stats', statsRouter);
router.use('/crisis', crisisRouter);
router.use('/narcan', narcanRespondersRouter);
router.use('/narcan', narcanAlertsRouter);
router.use('/narcan', narcanSubscribeRouter);
router.use('/stories', responderStoriesRouter);
router.use('/store', storeRouter);
router.use('/narcan/supply-chain', narcanSupplyChainRouter);
router.use('/stripe', stripeWebhookRouter);
router.use('/autopilot', autopilotSchedulerRouter);
router.use('/notifications', notificationsRouter);
router.use('/email', emailNotificationsRouter);
router.use('/analytics', analyticsRouter);
router.use('/2fa', twoFactorRouter);
router.use('/audit-logs', auditLogsRouter);
router.use('/heatmap', heatmapRouter);
router.use('/video-testimonials', videoTestimonialsRouter);

export default router;
